DROP TABLE `agent_credentials`;--> statement-breakpoint
DROP TABLE `agent_onboarding_progress`;--> statement-breakpoint
DROP TABLE `agent_sessions`;--> statement-breakpoint
DROP TABLE `agents`;--> statement-breakpoint
DROP TABLE `annuities`;--> statement-breakpoint
DROP TABLE `app_settings`;--> statement-breakpoint
DROP TABLE `appointments`;--> statement-breakpoint
DROP TABLE `audit_logs`;--> statement-breakpoint
DROP TABLE `carriers`;--> statement-breakpoint
DROP TABLE `client_links`;--> statement-breakpoint
DROP TABLE `clients`;--> statement-breakpoint
DROP TABLE `contact_submissions`;--> statement-breakpoint
DROP TABLE `expenses`;--> statement-breakpoint
DROP TABLE `graded_whole_life_policies`;--> statement-breakpoint
DROP TABLE `login_attempts`;--> statement-breakpoint
DROP TABLE `monthly_revenue_snapshots`;--> statement-breakpoint
DROP TABLE `password_reset_tokens`;--> statement-breakpoint
DROP TABLE `persistence_rate_snapshots`;--> statement-breakpoint
DROP TABLE `policies`;--> statement-breakpoint
DROP TABLE `quote_requests`;--> statement-breakpoint
DROP TABLE `referral_rewards`;--> statement-breakpoint
DROP TABLE `referrals`;--> statement-breakpoint
DROP TABLE `sales_entries`;--> statement-breakpoint
DROP TABLE `session_activity`;--> statement-breakpoint
DROP TABLE `users`;